"""Adiciona a coluna nome à tabela contato

Revision ID: 93e3e2815c70
Revises: fa957e257119
Create Date: 2024-12-12 21:57:20.988493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e3e2815c70'
down_revision = 'fa957e257119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(), nullable=True))
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
